echo ""
echo ", _                          , _     _____"
echo "/|/ \|)    _ |\    (|  |  |_//|/ \   () ||)    _          _"
echo " |__/|/\  |/ |/     |  |  |   |__/      ||/\  |/ /|/|/|  |/"
echo " |   |  |/|_/|_/     \/ \/    |       (/ |  |/|_/ | | |_/|_/"
echo ""
echo "Setup completed! Login to the site at http://localhost:8082/wp-admin/"
echo ""
echo "Username: admin"
echo "Password: password"
echo ""
echo "Or simply visit http://localhost:8082"
